#!/bin/sh

# This file is part of the KDE project
# Copyright (C) 2002,2003 Paul Chitescu <paulc-devel@null.ro>
# License: Open Source, Use On Your Own Risk
#
# Konqueror/Embedded RTF to HTML data filter
#
# Requires: sh, sed, unrtf
#
# Usage: in your konq-embedrc file,
#
# [MIME Handlers]
# */rtf,.rtf=|text/html|/path/to/this/file

# you shouldn't need to change anything below
case "$FILTER_URL" in
file:/*)
    unrtf --nopict --html `echo "$FILTER_URL" | sed 's,^file:,,'`
    ;;
*)
    tmpf=/tmp/.konqe-dl-$$.rtf
    cat >$tmpf
    unrtf --nopict --html $tmpf
    rm $tmpf
    ;;
esac
