#!/bin/sh

# This file is part of the KDE project
# Copyright (C) 2002 Paul Chitescu <paulc-devel@null.ro>
# License: Open Source, Use On Your Own Risk
#
# Konqueror/Embedded Plain Text to HTML data filter
#
# Requires: sh, sed
#
# Usage: in your konq-embedrc file,
#
# [MIME Handlers]
# text/*,.log,.sh=|text/html|/path/to/this/file

# you shouldn't need to change anything below
echo '<HTML><BODY><PRE>'
sed 's/&/\&amp;/g; s/"/\&quot;/g; s/</\&lt;/g; s/>/\&gt;/g'
echo '</PRE></BODY></HTML>'
